### ISSUE TITLE
Timer started at 0:01 on new map, then went back to normal after the map reopened

### ISSUE THREAD

**Issue by Wain4** [GreepTheSheep/openplanet-MXRandom#103] opened 2023-08-10 13:30 UTC
Timer started at 0:01 on new map, then went back to normal after the map reopened.
Tarpor VOD: https://www.twitch.tv/videos/1894946711?t=4h25m42s
Log: https://www.twitch.tv/videos/1894946711?t=4h31m50s
Not exactly related, but some more info about room updates: https://github.com/GreepTheSheep/openplanet-MXRandom/pull/99

**Comment by GreepTheSheep** [comment] 2023-08-10 13:52
Duplicate of #88

**Closed by GreepTheSheep** 2023-08-10 13:52 UTC
Labels: bug

**Comment by Wain4** [comment] 2023-08-10 15:40
#88 is related but not duplicate imo.
#88 breaks the run unrecoverably. In today's run, we were able to continue.

**Comment by GreepTheSheep** [comment] 2023-08-10 18:00
that's the same bug
